/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package io.openmessaging.connector.api.data;

import io.openmessaging.KeyValue;
import io.openmessaging.internal.DefaultKeyValue;
import java.util.Objects;
import java.util.Set;

/**
 * SourceDataEntries are generated by SourceTasks and passed to specific message queue to store.
 */
public class ConnectRecord {

    /**
     * eg.
     * if sink data from mq, targetPartition = topicName
     * if source data to mq, targetPartition = topicName
     */
    private String targetPartition;

    /**
     * Timestamp of the data entry.
     */
    private Long timestamp;

    /**
     * Schema of the data entry.
     */
    private Schema schema;

    /**
     * Payload of the data entry.
     */
    private Object data;

    /**
     * Position of record
     */
    private RecordPosition position;

    /**
     * Extension properties
     */
    private KeyValue extensions;

    public ConnectRecord(String targetPartition, RecordPartition recordPartition, RecordOffset recordOffset,
        Long timestamp) {
        this(targetPartition, recordPartition, recordOffset, timestamp, null, null);
    }

    public ConnectRecord(String targetPartition, RecordPartition recordPartition, RecordOffset recordOffset,
        Long timestamp, Schema schema,
        Object data) {
        this.targetPartition = targetPartition;
        this.position = new RecordPosition(recordPartition, recordOffset);
        this.schema = schema;
        this.timestamp = timestamp;
        this.data = data;
    }

    public String getTargetPartition() {
        return targetPartition;
    }

    public void setTargetPartition(String targetPartition) {
        this.targetPartition = targetPartition;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public Schema getSchema() {
        return schema;
    }

    public void setSchema(Schema schema) {
        this.schema = schema;
    }

    public Object getData() {
        return data;
    }

    public void setData(Object data) {
        this.data = data;
    }

    public KeyValue getExtensions() {
        return extensions;
    }

    public void setExtensions(KeyValue extensions) {
        this.extensions = extensions;
    }

    public void addExtension(KeyValue extensions) {
        if (this.extensions == null) {
            this.extensions = new DefaultKeyValue();
        }
        Set<String> keySet = extensions.keySet();
        for (String key : keySet) {
            this.extensions.put(key, extensions.getString(key));
        }
    }

    public void addExtension(String key, String value) {
        if (this.extensions == null) {
            this.extensions = new DefaultKeyValue();
        }
        this.extensions.put(key, value);
    }

    public String getExtension(String key) {
        if (this.extensions == null) {
            return null;
        }
        return this.extensions.getString(key);
    }

    public RecordPosition getPosition() {
        return position;
    }

    public void setPosition(RecordPosition position) {
        this.position = position;
    }

    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof ConnectRecord))
            return false;
        ConnectRecord that = (ConnectRecord) o;
        return Objects.equals(targetPartition, that.targetPartition) && Objects.equals(timestamp, that.timestamp) && Objects.equals(schema, that.schema) && Objects.equals(data, that.data) && Objects.equals(position, that.position) && Objects.equals(extensions, that.extensions);
    }

    @Override public int hashCode() {
        return Objects.hash(targetPartition, timestamp, schema, data, position, extensions);
    }

    @Override public String toString() {
        return "ConnectRecord{" +
            "targetPartition='" + targetPartition + '\'' +
            ", timestamp=" + timestamp +
            ", schema=" + schema +
            ", data=" + data +
            ", position=" + position +
            ", extensions=" + extensions +
            '}';
    }
}
