/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.openmessaging.connector.api.data;

/**
 * SourceDataEntries are generated by SourceTasks and passed to specific message queue to store.
 *
 * @version OMS 0.1.0
 * @since OMS 0.1.0
 */
public class SourceDataEntry extends DataEntry {

    public SourceDataEntry(byte[] sourcePartition,
        byte[] sourcePosition,
        Long timestamp,
        EntryType entryType,
        String queueName,
        Schema schema,
        Object[] payload) {
        super(timestamp, entryType, queueName, schema, payload);
        this.sourcePartition = sourcePartition;
        this.sourcePosition = sourcePosition;
    }

    /**
     * Partition of the data source.
     */
    private byte[] sourcePartition;

    /**
     * Position of current data entry of {@link SourceDataEntry#sourcePartition}.
     */
    private byte[] sourcePosition;

    public byte[] getSourcePartition() {
        return sourcePartition;
    }

    public void setSourcePartition(byte[] sourcePartition) {
        this.sourcePartition = sourcePartition;
    }

    public byte[] getSourcePosition() {
        return sourcePosition;
    }

    public void setSourcePosition(byte[] sourcePosition) {
        this.sourcePosition = sourcePosition;
    }
}
